version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: ./frontend_angular/Dockerfile.dev
    ports:
      - "8080:8080"

  nestjs-app:
    build:
      context: .
      dockerfile: ./backend_nest/Dockerfile.dev
    ports:
      - "3000:3000"
    # depends_on:
    #   - mysql-db

  # mysql-db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: bd_docker
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: 12qwasZX$
